# **NUMPY**

In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [16]:
#Comprobación de la versión de Numpy que tenemos en nuestro ordenador
print(np.__version__)

1.20.1


## **Matrices**

In [17]:
# Al objeto de matriz en Numpy se le llama (ndarray)

print(type(arr)) #La función type nos dice de que tipo es el objeto que le pasamos

<class 'numpy.ndarray'>


In [18]:
#Para crear un ndarray, podemos pasar una lista, tupla o cualquier objeto similar a una matriz en el array() método, y se convertirá en un ndarray

arr=np.array((1,2,3,4,5)) #Le hemos pasado una lista y la ha convertido en array
print(arr)

[1 2 3 4 5]


### Dimension en matrices

In [19]:
#MATRIZ 0-D.
#Una matriz de 0 dimensiones en un escalar, es decir, el elemento de una matriz
#Cada valor de una matriz es una matriz de 0-D

a=np.array(35)
print(type(a))
print(a)

<class 'numpy.ndarray'>
35


In [20]:
#MATRIZ 1-D.
b=np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [21]:
#MATRIZ 2-D.
#Una matriz que tiene matrices de dimension 1 es una matriz de 2D.
#Numpy tiene un submodulo dedicado a operaciones matriciales (numpy.mat)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
#MATRIZ 3-D.
#Una matriz que tiene matrices 2-D.
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
#(ndim) esto es un atributo -> nos devuelve el número entero de cuántas dimensiones es nuestra matriz.
#Se pueden crear matrices de las dimensiones que nosotros queramos
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

array_dim_5=np.array([1,2,3,4], ndmin=5)

print(array_dim_5)
print('number of dimensions: ', array_dim_5.ndim)

0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions:  5


### Indexación de matrices

Los índices en las matrices Numpy comienzan con el 0, lo que significa que el primer elemento tiene índice 0 y el segundo tiene índice 1

In [35]:
# Acceder a un elemento de la matriz
print(b)
print(b[0]) #1
print(b[1]) #2
print(b[2] + b[3]) #3+4=7



[1 2 3 4 5]
1
2
7


In [44]:
#Acceder a elementos de una matriz 2-D
print(c)
print('2n element on 1st dim: ', c[0,1]) #El primer elemento hace referencia a la dimension y el segundo al índice


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2n element on 1st dim:  2


In [45]:
#Acceder a elementos de una matriz 3-D
#Primero matrices, luego elementos
print(d)
print(d[0,1,2]) #Acceder al tercer elemento de la segunda matriz de la primera matriz

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [46]:
#Indexación negativa
#Sirve para acceder a una matriz desde el final


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
print(c)
print('Last element from 2nd dim: ', c[1,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Last element from 2nd dim:  6


### Slicing de una matriz

Cortar en python significa tomar elementos de un índice dado a otro índice dado.
**2 ejemplos usados:**

    - [start:end]
    - [start:end:step]
    
- Si no ponemos el inicio se considera 0
- Si no ponemos el end, su longitud se considera la de esa dimensión
- Si no ponemos el step se considera 1

In [71]:
array_simple= np.array([1,2,3,4,5,6,7])
print(array_simple[1:5]) #Dividir los elementos del índice 1 al 5
#El resultado incluye el índice inicial, pero excluye el índice final

#otros ejemplos:
print(array_simple[4:])
print(array_simple[:4])
#Slicing negativo
print(array_simple[-5:-3]) #Se empieza desde atrás de la matriz


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[3 4]


In [74]:
#Step (salto de números)
print(array_simple)

print(array_simple[1:5:2])
print(array_simple[::2])

[1 2 3 4 5 6 7]
[2 4]
[1 3 5 7]


In [78]:
#Cortar matrices de 2-D
array_compleja=np.array([[1,2,3,4,5],[6,7,8,9,10]])

#De la primera matriz, corta del índice 1 al 4
print(array_compleja[0, 1:4])

#De ambas matrices devuelve el índice 2
print(array_compleja[0:2, 2])

#De ambas matrices corte del índice 1 al 4.
print(array_compleja[0:2, 1:4]) 

[2 3 4]
[3 8]
[[2 3 4]
 [7 8 9]]


## **Tipos de datos**

Numpy tiene algunos tipos de datos adicionales, son un tipo de dato con un carácter.

**Los tipos de datos en Numpy y los carácteres usados para representarlos:**

- i - entero
- b - booleano
- u - entero sin signo
- f - flotar
- c - flotador complejo
- m - timedelta
- M - fecha y hora
- O - objeto
- S - cuerda
- U - cadena unicode
- V - fragmento de memoria fijo para otro tipo (vacío)
    

In [79]:
# (dtype) te dice de que tipo son los datos

matriz_strings=np.array(['apple', 'banana','cherry'])
matriz_integers=np.array([1,2,3,4,5,6])

print(matriz_strings.dtype)
print(matriz_integers.dtype)

<U6
int64


In [81]:
#Creación de matrices con un tipo de datos definidos

matriz=np.array([1,2,3,4,5], dtype='S')
print(matriz)
print(matriz.dtype) #Crea una matriz con una cadena de tipo de datos

matriz=np.array([1,2,3,4,5], dtype='i4')
print(matriz)
print(matriz.dtype) #Crea una matriz con datos enteros de 4 bytes

[b'1' b'2' b'3' b'4' b'5']
|S1
[1 2 3 4 5]
int32


In [89]:
#Conversión de matrices existentes
#(astype) esta función crea una copia de la matriz ya existente y le permite especificar el tipo de datos como parámetro

#Cambiar de flotante a entero usando 'i'
matriz=np.array([1.1, 2.1, 3.1])

nueva_matriz= matriz.astype('i')
print(nueva_matriz)

#Cambiar de entero a booleano
matriz=np.array([1, 0, 3])

matriz_booleano= matriz.astype(bool)
print(matriz_booleano)

[1 2 3]
[ True False  True]


# **Numpy Copy vs View**

**COPIAR:** La copia es propietaria de los datos y cualquier cambio realizado en la copia no afectará la matriz original, y cualquier cambio realizado en la matriz original no afectará la copia.


**VER:** La vista no es propietaria de los datos y cualquier cambio realizado en la vista afectará a la matriz original, y cualquier cambio realizado en la matriz original afectará la vista.




In [99]:
#Ejemplo de copiar una matriz

matriz_original=np.array([1,2,3,4,5,6,7,8,9,10])
copia_dela_original= matriz_original.copy()
matriz_original[4]=50

print("COPIAR: \n",matriz_original)
print(copia_dela_original)

print()
#Ejemplo de ver una matriz

matriz_original=np.array([1,2,3,4,5,6,7,8,9,10])
ver_original= matriz_original.view()
matriz_original[4]=50
ver_original[1]=20

print("VER:\n",matriz_original)
print(matriz_original)

COPIAR: 
 [ 1  2  3  4 50  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]

VER:
 [ 1 20  3  4 50  6  7  8  9 10]
[ 1 20  3  4 50  6  7  8  9 10]
