# **Exercise 1**

**STATEMENT:** Create a function that given an Array of a dimension, gives you a basic statistical summary of the data. If it detects that the array has more than one dimension, it should display an error message.

In [19]:
import numpy as np
import random 
import collections

random_list=np.array([random.randint(0,100) for i in range(10)]) #1dim

def statisticalSummaryOfArray(array):
    
    if array.ndim==1:
        print("The mean is: ", round(np.mean(array),2))  #Calculate mean
        print("The meadian is: ", round(np.median(array),2)) #Calculate median
        mode=collections.Counter(array).most_common(1)[0]
        print("The mode is: ", mode) #Calculate mode with collections' module
        print("The standard deviation is: ",round(np.std(array),2)) #Calculate standard deviation
    else:
        print("The dimension of the array is different from 1")
        
print("The random array has the next appearance:",random_list,"\n")
statisticalSummaryOfArray(random_list)


The random array has the next appearance: [39 84 68 52 23 64 61 30 86 86] 

The mean is:  59.3
The meadian is:  62.5
The mode is:  (86, 2)
The standard deviation is:  21.86


# **EXERCISE 2**

**STATEMENT:** Create a function that generates an NxN square of random numbers between 0 and 100.

In [322]:
from random import randint

user_number=int(input("Introduce a number: \n"))

def array5x5(number):
    array=[] #Create an empty array
    
    for i in range(number): #We will fill the whole array with the number introduced by the user
        row=[] #Create an empty row
        for j in range(number):
            row.append(randint(0,100)) #For each row we will fill it with the number given by the user 
        array.append(row) 
    
    return array

print("The array",user_number,"x",user_number,"is: \n")
array5x5(user_number)


Introduce a number: 
5
The array 5 x 5 is: 



[[44, 72, 32, 97, 32],
 [11, 20, 13, 52, 69],
 [8, 44, 76, 71, 84],
 [48, 68, 15, 69, 3],
 [34, 6, 94, 33, 45]]

# **Exercise 3**

**STATEMENT:** Create a function that donated a table of two dimensions, and calculated the totals per row and the totals per column.

In [18]:
import random

# 2-D random matrix 
random_matrix= np.random.randint(100, size=(5,5))
print(random_matrix)

#We will calculate the totalas per row and totals per column
def sumRowsAndColumns(random_matrix):
    sum_of_columns=np.sum(random_matrix, axis=0)
    sum_of_rows=np.sum(random_matrix, axis=1)
    print("The totals per column:\n",sum_of_columns)
    print("The totals per row:\n",sum_of_rows)

sumRowsAndColumns(random_matrix)

[[74 36 26 36  3]
 [46 99 13 21 66]
 [62 44  7  7  4]
 [20 10 81 71 90]
 [44 59  4 88 66]]
The totals per column:
 [246 248 131 223 229]
The totals per row:
 [175 245 124 272 261]


# **EXERCISE 4**

**STATEMENT:** Manually implements a function that calculates the correlation coefficient. Learn about its uses and interpretation.

In [43]:
#Target: find the correlation of a matrix

rng=np.random.default_rng(seed=26) #seed () is used to set the seed for the Python pseudo-random number generator algorithm.
random_array=rng.random((3,3))
print(random_array)

#We want to calculate the random_array's correlation 

def correlationCoeficient(array):
    correlation=np.corrcoef(array) 
    
    return correlation

print("\nThe coeficients of correlation are:\n",correlationCoeficient(random_array))


[[0.49159892 0.23439952 0.06760776]
 [0.7128582  0.8131152  0.54833668]
 [0.6343088  0.16919992 0.55433175]]

The coeficients of correlation are:
 [[ 1.          0.51441827  0.28019446]
 [ 0.51441827  1.         -0.67905203]
 [ 0.28019446 -0.67905203  1.        ]]


**We can access to a concrete matrix of correlations and explain the meaning**

 - **Explanation:** If we access to 1st column and 3rd column we can say that the coefficients of correlations are the next ones. That means the 2nd row and 1st column have a strong correlation with 0,932. For example, if Y were school dropout and X were students with worst marks, the countries with high levels of students with worst marks have at the same time high levels of school dropouts. The contrary explanation for those countries with low levels of bad students.



In [61]:
print(np.corrcoef(random_array[:,0],random_array[:,2]))
np.corrcoef(random_array[:,0],random_array[:,2])[1,0] #1 is 2nd row and 0 1st column


[[1.         0.93288652]
 [0.93288652 1.        ]]


0.9328865224496595